### ISSUE TITLE
How to add `About me`

### ISSUE THREAD

**Issue by dogvscat** [xiangming/landscape-plus#89]
I tried to add `About me `in widgets like `Category`,but it doesn't work. Any help?

**Comment by uniwolf** [comment]
+1

**Comment by tomByrer** [comment]
I'm not sure for `About me` since I don't know how spaces are handled, but here is how I made an `About` page:
1. new folder `/source/about/`
2. new file `/source/about/index.md`
3. add to `index.md`: 
```yml
title: About me
date: 2016-01-03 17:12:40
description: "All about meeeeee."
type: "about"

---
(text here)
```
4. In `/themes/landscape-plus/_config.yml` add a line under `menu:` to read: `  About: /about`

Should work.  Yes Hexo's documentation sometimes is hard to find what you are thinking.
