### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by ruoyi0531** [xiangming/landscape-plus#97]
代码高亮如何配置呢？

**Comment by xiangming** [comment]
在你hexo的`_config.yml`里面配置你的代码高亮。
```yml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
```
然后写代码时候，使用正确的markdown语法。
